### ISSUE TITLE
Cannot load eBPF program

### ISSUE THREAD

**Issue by pcy190** [atrosinenko/kbdysch#2]
On ubuntu 18.04
I've built the lkl.so and linked the kbdysch runtime successfully with the `USE_INVOKERS` option `OFF`.

But when I test the `bpffuzz` with following cmd
```
./bpffuzz init=/bin/sh < ../../ebpf_data/data
```
It shows that 
```
[    0.000000] Linux version 5.3.0+ (happy@ubuntu) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #1 Sun May 31 22:20:21 PDT 2020
[    0.000000] memblock address range: 0x7fdf7c000000 - 0x7fdf7ffff000
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 16159
[    0.000000] Kernel command line: init=/bin/sh
[    0.000000] Dentry cache hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.000000] Inode-cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory available: 64500k/65532k RAM
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 4096
[    0.000000] lkl: irqs initialized
[    0.000000] clocksource: lkl: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
...
Mounting all...
Cannot load eBPF program: Invalid system call number
```

seems `Invalid system call number`, 
but I check the syscall invoke instruction again
```
INVOKE_SYSCALL(state, bpf, BPF_PROG_LOAD , (long)&attr, sizeof(attr));
```
replace the `BPF_PROG_LOAD` with `LKL_BPF_PROG_LOAD` also fail.

**Comment by atrosinenko** [comment]
Hello @pcy190 

First, there is no need to pass the `init=/bin/sh` command line option (I'm not sure it is handled at all). On the other hand, `mem=32M` (or other value) could be helpful.

On the original issue, the syscall number here is not `BPF_PROG_LOAD`, it is something like `SYS_bpf` (and right, `LKL_` prefixed values should be used someday on LKL and not on the host kernel, but now it should work well when the host kernel is also Linux). Most probably, you need to re-configure your LKL-kernel (with `make menuconfig` or something similar) and rebuild it to enable support for bpf() syscall.

**Comment by pcy190** [comment]
Thanks a lot.
After setting the bpf syscall in the make config, it works.
